name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Current Directory
      run: pwd

    - name: Verify Docker Installation
      run: |
        sudo docker --version
        sudo systemctl status docker

    - name: Check Running Docker Services
      run: sudo docker ps -a

    - name: Stop Docker Container
      run: sudo docker stop csn-nginx || true

    - name: Delete the Docker Container
      run: sudo docker rm csn-nginx || true

    - name: Build Nginx Docker Image
      run: sudo docker build -t csn-nginx .

    - name: Run the Docker Container
      run: sudo docker run -d --name csn-nginx -p 8080:80 csn-nginx

    - name: Check Running Docker Services After Deployment
      run: sudo docker ps -a

    - name: Check Docker Container Logs
      run: sudo docker logs csn-nginx

    - name: Test the Web Service
      run: |
        echo "Waiting for the service to start..."
        sleep 10  # Wait for 10 seconds to give the service time to start
        curl -v http://localhost:8080 || (echo "Curl failed"; sudo docker logs csn-nginx)
